### ISSUE TITLE
Preparation of the guide for the meeting (issue #15 related)

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dgeometry#18]
The goal is to prepare the guide for drawing basic geometric elements in the dgeometry module.

**Comment by bugkarol** [comment]
Guide Jupyter
https://cocalc.com/projects/cdcf3856-3e8b-4d1c-bcb2-5c42ba749d83/files/UCZESTNICY/Guide_Source/Source/%5BPL%5D%5BGuide%5D%5BBasics%5DDgeometry%20basic%20operations.ipynb#id=c77f0e

Guide PDF
https://cocalc.com/projects/cdcf3856-3e8b-4d1c-bcb2-5c42ba749d83/files/%5BWIP%5D%20Guidelines/%5BPL%5D%5BGuide%5D%5BBasics%5DDgeometry%20basic%20operations.pdf
