### ISSUE TITLE
Guide for basic usage of dgeometry module and its development

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dgeometry#19]
The goal of issue is to create guide that explains how module `dgeometry.py` could be utilized and for its further growth.

**Comment by bartekvv4** [comment]
The goal of issue is to create guide that explains how module dgeometry.py could be utilized and for its further growth.

**Comment by szymonkozlowski080** [comment]
https://cocalc.com/projects/cdcf3856-3e8b-4d1c-bcb2-5c42ba749d83/files/%5BWIP%5D%20Guidelines/%5BPL%5D%5BGuide%5D%5BDrawing%5D%20Tworzenie%20klas%20do%20rysunk%C3%B3w%20in%C5%BCynierskich.pdf
