### ISSUE TITLE
Preparation of meeting and guide for maintenance of basic features of dgeometry module

### ISSUE THREAD

**Issue by bogumilchilinski** [bogumilchilinski/dgeometry#7]
The following actions are to do, in order to prepare the meeting and the guide:

- [x] #8

- [x] #9

- [x] #10

**Comment by amvdek** [comment]
The meeting was led by @bogumilchilinski

**Comment by Mk11-10** [comment]
Guide can be found in this PDF:
https://cocalc.com/projects/cdcf3856-3e8b-4d1c-bcb2-5c42ba749d83/files/%5BWIP%5D%20Guidelines/%5BPL%5D%5BGuide%5DDevelopment%20of%20set%20modules%20with%20Descriptive%20Geometry%20cases.pdf

Source to the guide can be found in this code:
https://cocalc.com/projects/cdcf3856-3e8b-4d1c-bcb2-5c42ba749d83/files/%5BWIP%5D%20Guidelines/%5BPL%5D%5BGuide%5DDevelopment%20of%20set%20modules%20with%20Descriptive%20Geometry%20cases.pdf
